stock <- read.csv(file.choose())
stocktimeseries <- ts(stock$Volume)
stocktimeseries
plot.ts(salestimeseries)
salestimeseriesdiff1 <- diff(salestimeseries, differences=1)
plot.ts(salestimeseriesdiff1)
adf.test((salestimeseries), alternative="stationary", k=0)
?adf.test
library(aTSA)
stationary.test(salestimeseriesdiff1)
stationary.test(salestimeseriesdiff1, method = "pp") 
stationary.test(salestimeseriesdiff1, method = "kpss")
acf(salestimeseriesdiff1, lag.max=20) 
acf(salestimeseriesdiff1, lag.max=20, plot=FALSE)
pacf(salestimeseriesdiff1, lag.max=20) 
pacf(salestimeseriesdiff1, lag.max=20, plot=FALSE)
sales <- scan("Alcohol_Sales.csv")
salestimeseries <- ts(sales)
plot.ts(salestimeseries)
salestimeseriesdiff1 <- diff(salestimeseries, differences=1)
plot.ts(salestimeseriesdiff1)
pacf(salestimeseriesdiff1, lag.max=20) 
pacf(salestimeseriesdiff1, lag.max=20, plot=FALSE)
?auto.arima()
library(forecast)
library(urca)
auto.arima(stock) # On the original Series
auto.arima(stocktimeseries) # On the time-series converted series
auto.arima(stocktimeseriesdiff1)